version: '3'
services:
  db:
    image: postgres:10.7 
    env_file:
        - database.env 
    ports:
        - "5432:5432"
  webserver:
    image: servianchallenge
    ports:
        - "80:3000"
    command: ["serve", "./TechChallengeApp updatedb"]
